services:
  aliaser:
    image: ghcr.io/codeshelldev/docker-network-aliaser:latest
    container_name: docker-network-aliaser
    environment:
      PREFIXES: my_prefix_1, my_prefix_2
      NETWORKS: my_network_1, my_network_2
      DOCKER_HOST: tcp://socket-proxy:2375
    depends_on:
      - socket-proxy
    restart: always
    networks:
      - backend

  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: docker-network-aliaser-socket-proxy
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      EVENTS: 1
      POST: 1
      PING: 1
      VERSION: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    read_only: true
    tmpfs:
      - /run
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
