# inside of example-project/ directory
services:
  postgres:
    image: postgres:16-alpine
    container_name: example-project-postgres
    labels:
      - my_prefix_1.enable=true
      - my_prefix_1.alias=db
    restart: unless-stopped
    networks:
      - backend
